sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.1.0

install:
  #build images
  - docker build -t devopschallenge .

before_script:
  - docker run --workdir=/app -v $PWD/:/app devopschallenge produce
  - docker run -d -p 8000:8000 --workdir=/app -v $PWD:/app devopschallenge serve

script:
  # - curl -L http://localhost:8080
  - docker ps
